name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3 # https://github.com/actions/checkout
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4 # https://github.com/docker/metadata-action
        with:
          images: wernight/beroux-builder
      - name: Test container image
        run: |
          set -ex
          docker compose build
          docker compose run --rm builder -- helm --version
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2 # https://github.com/docker/login-action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push production container image
        uses: docker/build-push-action@v4 # https://github.com/docker/build-push-action
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
